# Generated by Django 2.2.6 on 2019-11-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('reference', models.CharField(max_length=120)),
                ('genres', models.CharField(max_length=20)),
                ('authors', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000, null=True)),
                ('quote', models.CharField(max_length=400, null=True)),
                ('que', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage.passage')),
            ],
        ),
    ]
