# Generated by Django 2.2.6 on 2019-11-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('genres', models.CharField(max_length=20)),
                ('authors', models.CharField(max_length=50)),
                ('time_period', models.DateTimeField(verbose_name='date published')),
                ('location', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage.passage')),
            ],
        ),
    ]
