# Generated by Django 2.2.6 on 2019-11-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='title',
            new_name='source',
        ),
        migrations.AddField(
            model_name='passage',
            name='reference',
            field=models.CharField(max_length=120, null='true'),
            preserve_default='true',
        ),
    ]
