# Generated by Django 2.2.6 on 2019-11-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_passage_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='passage',
            name='que',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passage',
            name='quote',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='passage',
            name='time_period',
            field=models.DateField(),
        ),
    ]
