# Generated by Django 2.2.6 on 2019-11-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_auto_20191102_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='reference',
            field=models.CharField(max_length=120),
        ),
    ]
