# Generated by Django 2.2.6 on 2019-11-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0004_auto_20191103_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
